# -*- coding: utf-8 -*-
"""31st may

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B_QDCUJM5Yhi4ereJsVOdCoyh_S3gbVa

Cell 1: Install Dependencies
"""

!pip install -q ultralytics roboflow

"""check if gpu available"""

import torch
import ultralytics
ultralytics.checks()

# Check if GPU is available
print(f"Using Device: {torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'CPU'}")

"""download dataset form roboflow
https://universe.roboflow.com/janhavee/speed-breaker-detection-qklqp
"""

import os
from roboflow import Roboflow

# Initialize Roboflow
rf = Roboflow(api_key="8g93rOuycsap1QUVZhIU")
project = rf.workspace("janhavee").project("speed-breaker-detection-qklqp")
version = project.version(1)

# Download the dataset in yolov11 format
dataset = version.download("yolov11")

# Save the path to the data.yaml file
dataset_yaml = os.path.join(dataset.location, "data.yaml")
print(f"Dataset downloaded to: {dataset.location}")

"""train the model

"""

from ultralytics import YOLO

# Load a pretrained YOLOv11n model
model = YOLO('yolo11n.pt')

# Train the model
# data: path to your data.yaml
# epochs: number of training rounds
# imgsz: image size (standard is 640)
results = model.train(
    data=dataset_yaml,
    epochs=25,
    imgsz=640,
    plots=True,
    device=0 # Uses GPU
)

"""loss vs accuracy graph"""

# Validate the model on the test set
metrics = model.val()

print(f"Mean Average Precision (mAP50): {metrics.box.map50}")

# View training results (loss and accuracy plots)
from IPython.display import Image, display
display(Image(filename=f"{model.trainer.save_dir}/results.png", width=600))

"""here ,load the model and upload the video to get the speed breaker video output

"""

import os
import glob
import subprocess
from google.colab import files
from ultralytics import YOLO
from IPython.display import Video

# 1. Upload Video
print("Step 1: Upload your video file (e.g., .mp4, .mov, .avi):")
uploaded = files.upload()
if not uploaded:
    print("No file uploaded.")
else:
    video_name = list(uploaded.keys())[0]
    print(f"Successfully uploaded: {video_name}")

    # 2. Load the best weights from your YOLOv11 training
    # This assumes your training cell finished successfully
    model_path = '/content/best (7).pt'

    if not os.path.exists(model_path):
        print(f"Error: Model weights not found at {model_path}. Make sure training is finished.")
    else:
        best_model = YOLO(model_path)

        # 3. Run Inference with Optimized Settings
        # conf=0.3: ignores detections with less than 30% confidence
        # device=0: ensures GPU is used for fast processing
        print("Step 2: Processing video... this may take a moment.")
        results = best_model.predict(source=video_name, save=True, conf=0.3, imgsz=640, device=0)

        # 4. Find the result directory and convert to MP4 for viewing
        # YOLOv11 increments folders (predict, predict2, etc.), so we find the newest one
        latest_predict_dir = max(glob.glob('/content/runs/detect/predict*/'), key=os.path.getmtime)

        # YOLO saves videos as .avi by default in Colab; we need to find that file
        raw_output_list = glob.glob(os.path.join(latest_predict_dir, "*.avi")) + glob.glob(os.path.join(latest_predict_dir, "*.mp4"))
        raw_output = raw_output_list[0]

        final_output = "speed_breaker_detection_final.mp4"

        # Convert AVI (or raw MP4) to Web-Friendly H.264 MP4 using FFmpeg
        print("Step 3: Encoding video for display...")
        !ffmpeg -i "{raw_output}" -vcodec libx264 -f mp4 "{final_output}" -y -loglevel quiet

        # 5. Show Result
        print("\n--- SPEED BREAKER DETECTION RESULT ---")
        display(Video(final_output, embed=True, width=800))

        # Optional: Provide a download link for the processed video
        files.download(final_output)



"""**Here, in this dataset one logical mistake is there.There is two class in the dataset named Speed Bump and speedbump which contain same image,So i have merged 2 class into one class and re-trained the model**"""

import yaml

with open(dataset_yaml, 'r') as f:
    data = yaml.safe_load(f)

print(f"Number of classes: {data['nc']}")
print(f"Class names: {data['names']}")

import os

# Path to your training labels
label_path = os.path.join(dataset.location, "train/labels")
label_files = os.listdir(label_path)

classes_found = set()

# Read the first 100 label files to see what class IDs exist
for file in label_files[:100]:
    with open(os.path.join(label_path, file), 'r') as f:
        for line in f:
            class_id = line.split()[0]
            classes_found.add(class_id)

print(f"Class IDs found in your label files: {classes_found}")

import os

# Define the paths to your label folders
paths = [
    os.path.join(dataset.location, "train/labels"),
    os.path.join(dataset.location, "valid/labels"),
    os.path.join(dataset.location, "test/labels")
]

for path in paths:
    if os.path.exists(path):
        for label_file in os.listdir(path):
            file_path = os.path.join(path, label_file)

            with open(file_path, 'r') as f:
                lines = f.readlines()

            new_lines = []
            for line in lines:
                parts = line.split()
                if len(parts) > 0:
                    # Change class ID 1 to 0
                    parts[0] = '0'
                    new_lines.append(" ".join(parts) + "\n")

            with open(file_path, 'w') as f:
                f.writelines(new_lines)

print("✅ All labels successfully merged into Class 0!")

import yaml

# Path to your data.yaml
yaml_path = os.path.join(dataset.location, "data.yaml")

with open(yaml_path, 'r') as f:
    data = yaml.safe_load(f)

# Update values
data['nc'] = 1
data['names'] = ['Speed Bump']

# Save the updated file
with open(yaml_path, 'w') as f:
    yaml.dump(data, f)

print("✅ data.yaml updated: nc is now 1.")



"""**Re-trained with one class datatype**"""

from ultralytics import YOLO

# Load a pretrained YOLOv11n model
model = YOLO('yolo11n.pt')

# Train the model
# data: path to your data.yaml
# epochs: number of training rounds
# imgsz: image size (standard is 640)
results = model.train(
    data=dataset_yaml,
    epochs=25,
    imgsz=640,
    plots=True,
    device=0 # Uses GPU
)

import pandas as pd
import matplotlib.pyplot as plt

# Path to your latest results
results_path = '/content/runs/detect/train/results.csv'
df = pd.read_csv(results_path)
df.columns = [c.strip() for c in df.columns]

# Create Figure
fig, ax = plt.subplots(1, 2, figsize=(16, 6))

# Graph 1: Loss
ax[0].plot(df['epoch'], df['train/box_loss'], label='Train Box Loss', color='#1f77b4', linewidth=2)
ax[0].plot(df['epoch'], df['val/box_loss'], label='Val Box Loss', color='#ff7f0e', linestyle='--', linewidth=2)
ax[0].set_title('Training vs Validation Loss', fontsize=14)
ax[0].set_xlabel('Epochs')
ax[0].set_ylabel('Loss')
ax[0].legend()
ax[0].grid(True, alpha=0.3)

# Graph 2: Accuracy (mAP)
ax[1].plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP@50', color='#2ca02c', linewidth=2)
ax[1].plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP@50-95', color='#d62728', linewidth=2)
ax[1].set_title('Mean Average Precision (mAP)', fontsize=14)
ax[1].set_xlabel('Epochs')
ax[1].set_ylabel('mAP Score')
ax[1].legend()
ax[1].grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

from IPython.display import Image, display
import os

# List of visual results to show
visuals = [
    '/content/runs/detect/train/confusion_matrix.png',
    '/content/runs/detect/train/PR_curve.png',
    '/content/runs/detect/train/F1_curve.png'
]

for img in visuals:
    if os.path.exists(img):
        print(f"\n--- {img.split('/')[-1].replace('_', ' ').upper()} ---")
        display(Image(filename=img, width=700))



import os

# Path to your training labels
label_path = os.path.join(dataset.location, "train/labels")
label_files = os.listdir(label_path)

classes_found = set()

# Read the first 100 label files to see what class IDs exist
for file in label_files[:100]:
    with open(os.path.join(label_path, file), 'r') as f:
        for line in f:
            class_id = line.split()[0]
            classes_found.add(class_id)

print(f"Class IDs found in your label files: {classes_found}")



import os
import glob
import cv2
from google.colab import files
from ultralytics import YOLO
from IPython.display import Video, display

# 1. Upload Video
print("Step 1: Upload your video file:")
uploaded = files.upload()
if not uploaded:
    print("No file uploaded.")
else:
    video_name = list(uploaded.keys())[0]
    output_raw_path = "processed_raw.mp4"

    # 2. Load Model
    model_path = '/content/runs/detect/train/weights/best.pt' # Using your specific weight name
    if not os.path.exists(model_path):
        print(f"Error: Model weights not found at {model_path}")
    else:
        model = YOLO(model_path)

        # 3. Open Video for Processing
        cap = cv2.VideoCapture(video_name)
        width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
        height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps    = int(cap.get(cv2.CAP_PROP_FPS))

        # Define Video Writer
        fourcc = cv2.VideoWriter_fourcc(*'MP4V')
        out = cv2.VideoWriter(output_raw_path, fourcc, fps, (width, height))

        print("Step 2: Processing frames and adding warnings...")

        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            # Run YOLO detection
            results = model.predict(frame, conf=0.3, verbose=False)

            # Draw original YOLO detections
            annotated_frame = results[0].plot()

            # Custom Warning Logic
            # Check if any boxes were detected
            if len(results[0].boxes) > 0:
                # 1. Draw a Red Warning Banner at the top
                cv2.rectangle(annotated_frame, (0, 0), (width, 100), (0, 0, 255), -1)

                # 2. Add Warning Text
                cv2.putText(annotated_frame, "WARNING: SPEED BREAKER DETECTED", (int(width*0.1), 40),
                            cv2.FONT_HERSHEY_SIMPLEX, 1.2, (255, 255, 255), 3, cv2.LINE_AA)

                # 3. Add Slow Down Instruction
                cv2.putText(annotated_frame, ">>> SLOW DOWN SPEED NOW <<<", (int(width*0.2), 85),
                            cv2.FONT_HERSHEY_SIMPLEX, 1.0, (255, 255, 0), 2, cv2.LINE_AA)

            out.write(annotated_frame)

        cap.release()
        out.release()

        # 4. Convert to Web-Friendly MP4
        final_output = "speed_breaker_warning_final.mp4"
        print("Step 3: Finalizing video format...")
        !ffmpeg -i "{output_raw_path}" -vcodec libx264 -f mp4 "{final_output}" -y -loglevel quiet

        # 5. Show and Download Result
        print("\n--- DETECTION WITH ACTIVE WARNING SYSTEM ---")
        display(Video(final_output, embed=True, width=800))
        files.download(final_output)